package com.colecta.app.util

/**
 * Subset de países más comunes en numismática. Cada entrada: ISO-2, nombre ES,
 * y "slug" usado por Numista API (issuer).
 */
data class Country(val code: String, val name: String, val numistaSlug: String?)

val COUNTRIES: List<Country> = listOf(
    Country("ES", "España", "spain"),
    Country("FR", "Francia", "france"),
    Country("DE", "Alemania", "germany"),
    Country("IT", "Italia", "italy"),
    Country("PT", "Portugal", "portugal"),
    Country("GB", "Reino Unido", "united-kingdom"),
    Country("US", "Estados Unidos", "united-states"),
    Country("CA", "Canadá", "canada"),
    Country("MX", "México", "mexico"),
    Country("BR", "Brasil", "brazil"),
    Country("AR", "Argentina", "argentina"),
    Country("CL", "Chile", "chile"),
    Country("CO", "Colombia", "colombia"),
    Country("PE", "Perú", "peru"),
    Country("UY", "Uruguay", "uruguay"),
    Country("VE", "Venezuela", "venezuela"),
    Country("CU", "Cuba", "cuba"),
    Country("DO", "Rep. Dominicana", "dominican-republic"),
    Country("JP", "Japón", "japan"),
    Country("CN", "China", "china"),
    Country("RU", "Rusia", "russia"),
    Country("CH", "Suiza", "switzerland"),
    Country("NL", "Países Bajos", "netherlands"),
    Country("BE", "Bélgica", "belgium"),
    Country("AT", "Austria", "austria"),
    Country("SE", "Suecia", "sweden"),
    Country("NO", "Noruega", "norway"),
    Country("DK", "Dinamarca", "denmark"),
    Country("FI", "Finlandia", "finland"),
    Country("PL", "Polonia", "poland"),
    Country("GR", "Grecia", "greece"),
    Country("IE", "Irlanda", "ireland"),
    Country("AU", "Australia", "australia"),
    Country("NZ", "Nueva Zelanda", "new-zealand"),
    Country("IN", "India", "india"),
    Country("KR", "Corea del Sur", "korea-south"),
    Country("TR", "Turquía", "turkey"),
    Country("MA", "Marruecos", "morocco"),
    Country("ZA", "Sudáfrica", "south-africa"),
    Country("EG", "Egipto", "egypt"),
    Country("IL", "Israel", "israel"),
    Country("AE", "Emiratos Árabes", "united-arab-emirates"),
    Country("CZ", "Rep. Checa", "czech-republic"),
    Country("SK", "Eslovaquia", "slovakia"),
    Country("HU", "Hungría", "hungary"),
    Country("RO", "Rumanía", "romania"),
    Country("BG", "Bulgaria", "bulgaria"),
    Country("HR", "Croacia", "croatia"),
    Country("UA", "Ucrania", "ukraine"),
    Country("LU", "Luxemburgo", "luxembourg"),
    Country("MT", "Malta", "malta"),
    Country("CY", "Chipre", "cyprus"),
    Country("VA", "Vaticano", "vatican-city"),
    Country("SM", "San Marino", "san-marino"),
    Country("AD", "Andorra", "andorra"),
    Country("MC", "Mónaco", "monaco"),
    Country("IS", "Islandia", "iceland"),
)

fun findCountryByCode(code: String): Country? = COUNTRIES.firstOrNull { it.code.equals(code, ignoreCase = true) }
fun findCountryByName(name: String): Country? = COUNTRIES.firstOrNull { it.name.equals(name, ignoreCase = true) }
